
###

POST http://localhost:5000/api/auth/register

Content-Type: application/json

{
  "name": "Ibou Sarr",
  "email": "mouhamed@gmail.com",
  "password": "Kis@rrw3b"
}

###
GET http://localhost:5000/